version: '3'
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./web:/app
  redis:
    image: redis:7.0.9
    ports:
      - "6379:6379"
    volumes:
      - ./cache_data:/data
